sonata_media:
    class:
        media: App\Entity\SonataMediaMedia
        gallery: App\Entity\SonataMediaGallery
        gallery_item: App\Entity\SonataMediaGalleryItem
    db_driver: doctrine_orm # or doctrine_mongodb, it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default: # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http

            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100, quality: 70 }
                big: { width: 500, quality: 70 }

            
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory: '%kernel.project_dir%/public/uploads/media'
            create: false


           
    
    